### ISSUE TITLE
solarflare ef_vi

### ISSUE THREAD

**Issue by fengglfengdi** [hanshuebner/solarflare-tests#1]
help!!!
I use solarflare first time , I don't know how to read the UDP data .
when 
 enum ef_pd_flags pd_flags = EF_PD_DEFAULT  is OK ,but can't read data.
enum ef_pd_flags pd_flags = EF_PD_RX_PACKED_STREAM is wrong and ef_pd_alloc_by_name return -22.
thank you!

**Comment by hanshuebner** [comment]
Sorry, I don’t have the hardware anymore and cannot support this repository.
